### ISSUE TITLE
Metadata is missing

### ISSUE THREAD

**Issue by bbhtt** [flathub/io.github.Hexchat.Plugin.Perl#3]
This points to the upstream metainfo file https://github.com/flathub/io.github.Hexchat.Plugin.Perl/blob/8fb2aeec9e11bdc57584b4dd81e1e33fb9da209e/io.github.Hexchat.Plugin.Perl.json#L63 but neither the 2.14.3 archive nor git has that file https://github.com/hexchat/hexchat/tree/master/data/misc.

I guess as a result this doesn't show up in GNOME Software as an addon/separate app.

**Comment by TingPing** [comment]
The file is here: https://github.com/hexchat/hexchat/blob/master/data/misc/io.github.Hexchat.Plugin.metainfo.xml.in

It is dynamically generated for all plugins.

You can backport this patch: https://github.com/hexchat/hexchat/commit/2dd7636134f31d1f6f931f6adb0c33b3b5c12a34

**Comment by bbhtt** [comment]
Ah, thank you. I was looking at the filename.
